#ifndef _COMMON_INC_
#define _COMMON_INC_

#define PI 3.1415926535897932384626433832795


float pow2(float x)
{
	return x * x;
}

float pow3(float x)
{
	return x * x * x;
}

float pow4(float x)
{
	return x * x * x * x;
}

float pow5(float x)
{
	return x * x * x * x * x;
}

vec3 pow2(vec3 x)
{
	return x * x;
}

vec3 pow3(vec3 x)
{
	return x * x * x;
}

vec3 pow4(vec3 x)
{
	return x * x * x * x;
}

vec3 pow5(vec3 x)
{
	return x * x * x * x * x;
}

#endif
