/****************************************************************************
Copyright (c) 2017 LiangYue.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sub license, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
****************************************************************************/

#include "_CrossEngine.h"


namespace CrossEngine {

	typedef struct GLEnumString {
		uint32_t value;
		const char *text;
	} GLEnumString;

	static const GLEnumString glEnumStrings[] = {
		GL_DEPTH_BUFFER_BIT, "GL_DEPTH_BUFFER_BIT",
		GL_STENCIL_BUFFER_BIT, "GL_STENCIL_BUFFER_BIT",
		GL_COLOR_BUFFER_BIT, "GL_COLOR_BUFFER_BIT",
		GL_FALSE, "GL_FALSE",
		GL_TRUE, "GL_TRUE",
		GL_POINTS, "GL_POINTS",
		GL_LINES, "GL_LINES",
		GL_LINE_LOOP, "GL_LINE_LOOP",
		GL_LINE_STRIP, "GL_LINE_STRIP",
		GL_TRIANGLES, "GL_TRIANGLES",
		GL_TRIANGLE_STRIP, "GL_TRIANGLE_STRIP",
		GL_TRIANGLE_FAN, "GL_TRIANGLE_FAN",
		GL_ZERO, "GL_ZERO",
		GL_ONE, "GL_ONE",
		GL_SRC_COLOR, "GL_SRC_COLOR",
		GL_ONE_MINUS_SRC_COLOR, "GL_ONE_MINUS_SRC_COLOR",
		GL_SRC_ALPHA, "GL_SRC_ALPHA",
		GL_ONE_MINUS_SRC_ALPHA, "GL_ONE_MINUS_SRC_ALPHA",
		GL_DST_ALPHA, "GL_DST_ALPHA",
		GL_ONE_MINUS_DST_ALPHA, "GL_ONE_MINUS_DST_ALPHA",
		GL_DST_COLOR, "GL_DST_COLOR",
		GL_ONE_MINUS_DST_COLOR, "GL_ONE_MINUS_DST_COLOR",
		GL_SRC_ALPHA_SATURATE, "GL_SRC_ALPHA_SATURATE",
		GL_FUNC_ADD, "GL_FUNC_ADD",
		GL_BLEND_EQUATION, "GL_BLEND_EQUATION",
		GL_BLEND_EQUATION_RGB, "GL_BLEND_EQUATION_RGB",
		GL_BLEND_EQUATION_ALPHA, "GL_BLEND_EQUATION_ALPHA",
		GL_FUNC_SUBTRACT, "GL_FUNC_SUBTRACT",
		GL_FUNC_REVERSE_SUBTRACT, "GL_FUNC_REVERSE_SUBTRACT",
		GL_BLEND_DST_RGB, "GL_BLEND_DST_RGB",
		GL_BLEND_SRC_RGB, "GL_BLEND_SRC_RGB",
		GL_BLEND_DST_ALPHA, "GL_BLEND_DST_ALPHA",
		GL_BLEND_SRC_ALPHA, "GL_BLEND_SRC_ALPHA",
		GL_CONSTANT_COLOR, "GL_CONSTANT_COLOR",
		GL_ONE_MINUS_CONSTANT_COLOR, "GL_ONE_MINUS_CONSTANT_COLOR",
		GL_CONSTANT_ALPHA, "GL_CONSTANT_ALPHA",
		GL_ONE_MINUS_CONSTANT_ALPHA, "GL_ONE_MINUS_CONSTANT_ALPHA",
		GL_BLEND_COLOR, "GL_BLEND_COLOR",
		GL_ARRAY_BUFFER, "GL_ARRAY_BUFFER",
		GL_ELEMENT_ARRAY_BUFFER, "GL_ELEMENT_ARRAY_BUFFER",
		GL_ARRAY_BUFFER_BINDING, "GL_ARRAY_BUFFER_BINDING",
		GL_ELEMENT_ARRAY_BUFFER_BINDING, "GL_ELEMENT_ARRAY_BUFFER_BINDING",
		GL_STREAM_DRAW, "GL_STREAM_DRAW",
		GL_STATIC_DRAW, "GL_STATIC_DRAW",
		GL_DYNAMIC_DRAW, "GL_DYNAMIC_DRAW",
		GL_BUFFER_SIZE, "GL_BUFFER_SIZE",
		GL_BUFFER_USAGE, "GL_BUFFER_USAGE",
		GL_CURRENT_VERTEX_ATTRIB, "GL_CURRENT_VERTEX_ATTRIB",
		GL_FRONT, "GL_FRONT",
		GL_BACK, "GL_BACK",
		GL_FRONT_AND_BACK, "GL_FRONT_AND_BACK",
		GL_TEXTURE_2D, "GL_TEXTURE_2D",
		GL_CULL_FACE, "GL_CULL_FACE",
		GL_BLEND, "GL_BLEND",
		GL_DITHER, "GL_DITHER",
		GL_STENCIL_TEST, "GL_STENCIL_TEST",
		GL_DEPTH_TEST, "GL_DEPTH_TEST",
		GL_SCISSOR_TEST, "GL_SCISSOR_TEST",
		GL_POLYGON_OFFSET_FILL, "GL_POLYGON_OFFSET_FILL",
		GL_SAMPLE_ALPHA_TO_COVERAGE, "GL_SAMPLE_ALPHA_TO_COVERAGE",
		GL_SAMPLE_COVERAGE, "GL_SAMPLE_COVERAGE",
		GL_NO_ERROR, "GL_NO_ERROR",
		GL_INVALID_ENUM, "GL_INVALID_ENUM",
		GL_INVALID_VALUE, "GL_INVALID_VALUE",
		GL_INVALID_OPERATION, "GL_INVALID_OPERATION",
		GL_OUT_OF_MEMORY, "GL_OUT_OF_MEMORY",
		GL_CW, "GL_CW",
		GL_CCW, "GL_CCW",
		GL_LINE_WIDTH, "GL_LINE_WIDTH",
		GL_ALIASED_POINT_SIZE_RANGE, "GL_ALIASED_POINT_SIZE_RANGE",
		GL_ALIASED_LINE_WIDTH_RANGE, "GL_ALIASED_LINE_WIDTH_RANGE",
		GL_CULL_FACE_MODE, "GL_CULL_FACE_MODE",
		GL_FRONT_FACE, "GL_FRONT_FACE",
		GL_DEPTH_RANGE, "GL_DEPTH_RANGE",
		GL_DEPTH_WRITEMASK, "GL_DEPTH_WRITEMASK",
		GL_DEPTH_CLEAR_VALUE, "GL_DEPTH_CLEAR_VALUE",
		GL_DEPTH_FUNC, "GL_DEPTH_FUNC",
		GL_STENCIL_CLEAR_VALUE, "GL_STENCIL_CLEAR_VALUE",
		GL_STENCIL_FUNC, "GL_STENCIL_FUNC",
		GL_STENCIL_FAIL, "GL_STENCIL_FAIL",
		GL_STENCIL_PASS_DEPTH_FAIL, "GL_STENCIL_PASS_DEPTH_FAIL",
		GL_STENCIL_PASS_DEPTH_PASS, "GL_STENCIL_PASS_DEPTH_PASS",
		GL_STENCIL_REF, "GL_STENCIL_REF",
		GL_STENCIL_VALUE_MASK, "GL_STENCIL_VALUE_MASK",
		GL_STENCIL_WRITEMASK, "GL_STENCIL_WRITEMASK",
		GL_STENCIL_BACK_FUNC, "GL_STENCIL_BACK_FUNC",
		GL_STENCIL_BACK_FAIL, "GL_STENCIL_BACK_FAIL",
		GL_STENCIL_BACK_PASS_DEPTH_FAIL, "GL_STENCIL_BACK_PASS_DEPTH_FAIL",
		GL_STENCIL_BACK_PASS_DEPTH_PASS, "GL_STENCIL_BACK_PASS_DEPTH_PASS",
		GL_STENCIL_BACK_REF, "GL_STENCIL_BACK_REF",
		GL_STENCIL_BACK_VALUE_MASK, "GL_STENCIL_BACK_VALUE_MASK",
		GL_STENCIL_BACK_WRITEMASK, "GL_STENCIL_BACK_WRITEMASK",
		GL_VIEWPORT, "GL_VIEWPORT",
		GL_SCISSOR_BOX, "GL_SCISSOR_BOX",
		GL_COLOR_CLEAR_VALUE, "GL_COLOR_CLEAR_VALUE",
		GL_COLOR_WRITEMASK, "GL_COLOR_WRITEMASK",
		GL_UNPACK_ALIGNMENT, "GL_UNPACK_ALIGNMENT",
		GL_PACK_ALIGNMENT, "GL_PACK_ALIGNMENT",
		GL_MAX_TEXTURE_SIZE, "GL_MAX_TEXTURE_SIZE",
		GL_MAX_VIEWPORT_DIMS, "GL_MAX_VIEWPORT_DIMS",
		GL_SUBPIXEL_BITS, "GL_SUBPIXEL_BITS",
		GL_RED_BITS, "GL_RED_BITS",
		GL_GREEN_BITS, "GL_GREEN_BITS",
		GL_BLUE_BITS, "GL_BLUE_BITS",
		GL_ALPHA_BITS, "GL_ALPHA_BITS",
		GL_DEPTH_BITS, "GL_DEPTH_BITS",
		GL_STENCIL_BITS, "GL_STENCIL_BITS",
		GL_POLYGON_OFFSET_UNITS, "GL_POLYGON_OFFSET_UNITS",
		GL_POLYGON_OFFSET_FACTOR, "GL_POLYGON_OFFSET_FACTOR",
		GL_TEXTURE_BINDING_2D, "GL_TEXTURE_BINDING_2D",
		GL_SAMPLE_BUFFERS, "GL_SAMPLE_BUFFERS",
		GL_SAMPLES, "GL_SAMPLES",
		GL_SAMPLE_COVERAGE_VALUE, "GL_SAMPLE_COVERAGE_VALUE",
		GL_SAMPLE_COVERAGE_INVERT, "GL_SAMPLE_COVERAGE_INVERT",
		GL_NUM_COMPRESSED_TEXTURE_FORMATS, "GL_NUM_COMPRESSED_TEXTURE_FORMATS",
		GL_COMPRESSED_TEXTURE_FORMATS, "GL_COMPRESSED_TEXTURE_FORMATS",
		GL_DONT_CARE, "GL_DONT_CARE",
		GL_FASTEST, "GL_FASTEST",
		GL_NICEST, "GL_NICEST",
		GL_GENERATE_MIPMAP_HINT, "GL_GENERATE_MIPMAP_HINT",
		GL_BYTE, "GL_BYTE",
		GL_UNSIGNED_BYTE, "GL_UNSIGNED_BYTE",
		GL_SHORT, "GL_SHORT",
		GL_UNSIGNED_SHORT, "GL_UNSIGNED_SHORT",
		GL_INT, "GL_INT",
		GL_UNSIGNED_INT, "GL_UNSIGNED_INT",
		GL_FLOAT, "GL_FLOAT",
		GL_FIXED, "GL_FIXED",
		GL_DEPTH_COMPONENT, "GL_DEPTH_COMPONENT",
		GL_ALPHA, "GL_ALPHA",
		GL_RGB, "GL_RGB",
		GL_RGBA, "GL_RGBA",
		GL_LUMINANCE, "GL_LUMINANCE",
		GL_LUMINANCE_ALPHA, "GL_LUMINANCE_ALPHA",
		GL_UNSIGNED_SHORT_4_4_4_4, "GL_UNSIGNED_SHORT_4_4_4_4",
		GL_UNSIGNED_SHORT_5_5_5_1, "GL_UNSIGNED_SHORT_5_5_5_1",
		GL_UNSIGNED_SHORT_5_6_5, "GL_UNSIGNED_SHORT_5_6_5",
		GL_FRAGMENT_SHADER, "GL_FRAGMENT_SHADER",
		GL_VERTEX_SHADER, "GL_VERTEX_SHADER",
		GL_MAX_VERTEX_ATTRIBS, "GL_MAX_VERTEX_ATTRIBS",
		GL_MAX_VERTEX_UNIFORM_VECTORS, "GL_MAX_VERTEX_UNIFORM_VECTORS",
		GL_MAX_VARYING_VECTORS, "GL_MAX_VARYING_VECTORS",
		GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS, "GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS",
		GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS, "GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS",
		GL_MAX_TEXTURE_IMAGE_UNITS, "GL_MAX_TEXTURE_IMAGE_UNITS",
		GL_MAX_FRAGMENT_UNIFORM_VECTORS, "GL_MAX_FRAGMENT_UNIFORM_VECTORS",
		GL_SHADER_TYPE, "GL_SHADER_TYPE",
		GL_DELETE_STATUS, "GL_DELETE_STATUS",
		GL_LINK_STATUS, "GL_LINK_STATUS",
		GL_VALIDATE_STATUS, "GL_VALIDATE_STATUS",
		GL_ATTACHED_SHADERS, "GL_ATTACHED_SHADERS",
		GL_ACTIVE_UNIFORMS, "GL_ACTIVE_UNIFORMS",
		GL_ACTIVE_UNIFORM_MAX_LENGTH, "GL_ACTIVE_UNIFORM_MAX_LENGTH",
		GL_ACTIVE_ATTRIBUTES, "GL_ACTIVE_ATTRIBUTES",
		GL_ACTIVE_ATTRIBUTE_MAX_LENGTH, "GL_ACTIVE_ATTRIBUTE_MAX_LENGTH",
		GL_SHADING_LANGUAGE_VERSION, "GL_SHADING_LANGUAGE_VERSION",
		GL_CURRENT_PROGRAM, "GL_CURRENT_PROGRAM",
		GL_NEVER, "GL_NEVER",
		GL_LESS, "GL_LESS",
		GL_EQUAL, "GL_EQUAL",
		GL_LEQUAL, "GL_LEQUAL",
		GL_GREATER, "GL_GREATER",
		GL_NOTEQUAL, "GL_NOTEQUAL",
		GL_GEQUAL, "GL_GEQUAL",
		GL_ALWAYS, "GL_ALWAYS",
		GL_KEEP, "GL_KEEP",
		GL_REPLACE, "GL_REPLACE",
		GL_INCR, "GL_INCR",
		GL_DECR, "GL_DECR",
		GL_INVERT, "GL_INVERT",
		GL_INCR_WRAP, "GL_INCR_WRAP",
		GL_DECR_WRAP, "GL_DECR_WRAP",
		GL_VENDOR, "GL_VENDOR",
		GL_RENDERER, "GL_RENDERER",
		GL_VERSION, "GL_VERSION",
		GL_EXTENSIONS, "GL_EXTENSIONS",
		GL_NEAREST, "GL_NEAREST",
		GL_LINEAR, "GL_LINEAR",
		GL_NEAREST_MIPMAP_NEAREST, "GL_NEAREST_MIPMAP_NEAREST",
		GL_LINEAR_MIPMAP_NEAREST, "GL_LINEAR_MIPMAP_NEAREST",
		GL_NEAREST_MIPMAP_LINEAR, "GL_NEAREST_MIPMAP_LINEAR",
		GL_LINEAR_MIPMAP_LINEAR, "GL_LINEAR_MIPMAP_LINEAR",
		GL_TEXTURE_MAG_FILTER, "GL_TEXTURE_MAG_FILTER",
		GL_TEXTURE_MIN_FILTER, "GL_TEXTURE_MIN_FILTER",
		GL_TEXTURE_WRAP_S, "GL_TEXTURE_WRAP_S",
		GL_TEXTURE_WRAP_T, "GL_TEXTURE_WRAP_T",
		GL_TEXTURE, "GL_TEXTURE",
		GL_TEXTURE_CUBE_MAP, "GL_TEXTURE_CUBE_MAP",
		GL_TEXTURE_BINDING_CUBE_MAP, "GL_TEXTURE_BINDING_CUBE_MAP",
		GL_TEXTURE_CUBE_MAP_POSITIVE_X, "GL_TEXTURE_CUBE_MAP_POSITIVE_X",
		GL_TEXTURE_CUBE_MAP_NEGATIVE_X, "GL_TEXTURE_CUBE_MAP_NEGATIVE_X",
		GL_TEXTURE_CUBE_MAP_POSITIVE_Y, "GL_TEXTURE_CUBE_MAP_POSITIVE_Y",
		GL_TEXTURE_CUBE_MAP_NEGATIVE_Y, "GL_TEXTURE_CUBE_MAP_NEGATIVE_Y",
		GL_TEXTURE_CUBE_MAP_POSITIVE_Z, "GL_TEXTURE_CUBE_MAP_POSITIVE_Z",
		GL_TEXTURE_CUBE_MAP_NEGATIVE_Z, "GL_TEXTURE_CUBE_MAP_NEGATIVE_Z",
		GL_MAX_CUBE_MAP_TEXTURE_SIZE, "GL_MAX_CUBE_MAP_TEXTURE_SIZE",
		GL_TEXTURE0, "GL_TEXTURE0",
		GL_TEXTURE1, "GL_TEXTURE1",
		GL_TEXTURE2, "GL_TEXTURE2",
		GL_TEXTURE3, "GL_TEXTURE3",
		GL_TEXTURE4, "GL_TEXTURE4",
		GL_TEXTURE5, "GL_TEXTURE5",
		GL_TEXTURE6, "GL_TEXTURE6",
		GL_TEXTURE7, "GL_TEXTURE7",
		GL_TEXTURE8, "GL_TEXTURE8",
		GL_TEXTURE9, "GL_TEXTURE9",
		GL_TEXTURE10, "GL_TEXTURE10",
		GL_TEXTURE11, "GL_TEXTURE11",
		GL_TEXTURE12, "GL_TEXTURE12",
		GL_TEXTURE13, "GL_TEXTURE13",
		GL_TEXTURE14, "GL_TEXTURE14",
		GL_TEXTURE15, "GL_TEXTURE15",
		GL_TEXTURE16, "GL_TEXTURE16",
		GL_TEXTURE17, "GL_TEXTURE17",
		GL_TEXTURE18, "GL_TEXTURE18",
		GL_TEXTURE19, "GL_TEXTURE19",
		GL_TEXTURE20, "GL_TEXTURE20",
		GL_TEXTURE21, "GL_TEXTURE21",
		GL_TEXTURE22, "GL_TEXTURE22",
		GL_TEXTURE23, "GL_TEXTURE23",
		GL_TEXTURE24, "GL_TEXTURE24",
		GL_TEXTURE25, "GL_TEXTURE25",
		GL_TEXTURE26, "GL_TEXTURE26",
		GL_TEXTURE27, "GL_TEXTURE27",
		GL_TEXTURE28, "GL_TEXTURE28",
		GL_TEXTURE29, "GL_TEXTURE29",
		GL_TEXTURE30, "GL_TEXTURE30",
		GL_TEXTURE31, "GL_TEXTURE31",
		GL_ACTIVE_TEXTURE, "GL_ACTIVE_TEXTURE",
		GL_REPEAT, "GL_REPEAT",
		GL_CLAMP_TO_EDGE, "GL_CLAMP_TO_EDGE",
		GL_MIRRORED_REPEAT, "GL_MIRRORED_REPEAT",
		GL_FLOAT_VEC2, "GL_FLOAT_VEC2",
		GL_FLOAT_VEC3, "GL_FLOAT_VEC3",
		GL_FLOAT_VEC4, "GL_FLOAT_VEC4",
		GL_INT_VEC2, "GL_INT_VEC2",
		GL_INT_VEC3, "GL_INT_VEC3",
		GL_INT_VEC4, "GL_INT_VEC4",
		GL_BOOL, "GL_BOOL",
		GL_BOOL_VEC2, "GL_BOOL_VEC2",
		GL_BOOL_VEC3, "GL_BOOL_VEC3",
		GL_BOOL_VEC4, "GL_BOOL_VEC4",
		GL_FLOAT_MAT2, "GL_FLOAT_MAT2",
		GL_FLOAT_MAT3, "GL_FLOAT_MAT3",
		GL_FLOAT_MAT4, "GL_FLOAT_MAT4",
		GL_SAMPLER_2D, "GL_SAMPLER_2D",
		GL_SAMPLER_CUBE, "GL_SAMPLER_CUBE",
		GL_VERTEX_ATTRIB_ARRAY_ENABLED, "GL_VERTEX_ATTRIB_ARRAY_ENABLED",
		GL_VERTEX_ATTRIB_ARRAY_SIZE, "GL_VERTEX_ATTRIB_ARRAY_SIZE",
		GL_VERTEX_ATTRIB_ARRAY_STRIDE, "GL_VERTEX_ATTRIB_ARRAY_STRIDE",
		GL_VERTEX_ATTRIB_ARRAY_TYPE, "GL_VERTEX_ATTRIB_ARRAY_TYPE",
		GL_VERTEX_ATTRIB_ARRAY_NORMALIZED, "GL_VERTEX_ATTRIB_ARRAY_NORMALIZED",
		GL_VERTEX_ATTRIB_ARRAY_POINTER, "GL_VERTEX_ATTRIB_ARRAY_POINTER",
		GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING, "GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING",
		GL_IMPLEMENTATION_COLOR_READ_TYPE, "GL_IMPLEMENTATION_COLOR_READ_TYPE",
		GL_IMPLEMENTATION_COLOR_READ_FORMAT, "GL_IMPLEMENTATION_COLOR_READ_FORMAT",
		GL_COMPILE_STATUS, "GL_COMPILE_STATUS",
		GL_INFO_LOG_LENGTH, "GL_INFO_LOG_LENGTH",
		GL_SHADER_SOURCE_LENGTH, "GL_SHADER_SOURCE_LENGTH",
		GL_SHADER_COMPILER, "GL_SHADER_COMPILER",
		GL_SHADER_BINARY_FORMATS, "GL_SHADER_BINARY_FORMATS",
		GL_NUM_SHADER_BINARY_FORMATS, "GL_NUM_SHADER_BINARY_FORMATS",
		GL_LOW_FLOAT, "GL_LOW_FLOAT",
		GL_MEDIUM_FLOAT, "GL_MEDIUM_FLOAT",
		GL_HIGH_FLOAT, "GL_HIGH_FLOAT",
		GL_LOW_INT, "GL_LOW_INT",
		GL_MEDIUM_INT, "GL_MEDIUM_INT",
		GL_HIGH_INT, "GL_HIGH_INT",
		GL_FRAMEBUFFER, "GL_FRAMEBUFFER",
		GL_RENDERBUFFER, "GL_RENDERBUFFER",
		GL_RGBA4, "GL_RGBA4",
		GL_RGB5_A1, "GL_RGB5_A1",
		GL_RGB565, "GL_RGB565",
		GL_DEPTH_COMPONENT16, "GL_DEPTH_COMPONENT16",
		GL_STENCIL_INDEX8, "GL_STENCIL_INDEX8",
		GL_RENDERBUFFER_WIDTH, "GL_RENDERBUFFER_WIDTH",
		GL_RENDERBUFFER_HEIGHT, "GL_RENDERBUFFER_HEIGHT",
		GL_RENDERBUFFER_INTERNAL_FORMAT, "GL_RENDERBUFFER_INTERNAL_FORMAT",
		GL_RENDERBUFFER_RED_SIZE, "GL_RENDERBUFFER_RED_SIZE",
		GL_RENDERBUFFER_GREEN_SIZE, "GL_RENDERBUFFER_GREEN_SIZE",
		GL_RENDERBUFFER_BLUE_SIZE, "GL_RENDERBUFFER_BLUE_SIZE",
		GL_RENDERBUFFER_ALPHA_SIZE, "GL_RENDERBUFFER_ALPHA_SIZE",
		GL_RENDERBUFFER_DEPTH_SIZE, "GL_RENDERBUFFER_DEPTH_SIZE",
		GL_RENDERBUFFER_STENCIL_SIZE, "GL_RENDERBUFFER_STENCIL_SIZE",
		GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE, "GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE",
		GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME, "GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME",
		GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL, "GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL",
		GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE, "GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE",
		GL_COLOR_ATTACHMENT0, "GL_COLOR_ATTACHMENT0",
		GL_DEPTH_ATTACHMENT, "GL_DEPTH_ATTACHMENT",
		GL_STENCIL_ATTACHMENT, "GL_STENCIL_ATTACHMENT",
		GL_NONE, "GL_NONE",
		GL_FRAMEBUFFER_COMPLETE, "GL_FRAMEBUFFER_COMPLETE",
		GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT, "GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT",
		GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT, "GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT",
		GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS, "GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS",
		GL_FRAMEBUFFER_UNSUPPORTED, "GL_FRAMEBUFFER_UNSUPPORTED",
		GL_FRAMEBUFFER_BINDING, "GL_FRAMEBUFFER_BINDING",
		GL_RENDERBUFFER_BINDING, "GL_RENDERBUFFER_BINDING",
		GL_MAX_RENDERBUFFER_SIZE, "GL_MAX_RENDERBUFFER_SIZE",
		GL_INVALID_FRAMEBUFFER_OPERATION, "GL_INVALID_FRAMEBUFFER_OPERATION",
		GL_READ_BUFFER, "GL_READ_BUFFER",
		GL_UNPACK_ROW_LENGTH, "GL_UNPACK_ROW_LENGTH",
		GL_UNPACK_SKIP_ROWS, "GL_UNPACK_SKIP_ROWS",
		GL_UNPACK_SKIP_PIXELS, "GL_UNPACK_SKIP_PIXELS",
		GL_PACK_ROW_LENGTH, "GL_PACK_ROW_LENGTH",
		GL_PACK_SKIP_ROWS, "GL_PACK_SKIP_ROWS",
		GL_PACK_SKIP_PIXELS, "GL_PACK_SKIP_PIXELS",
		GL_COLOR, "GL_COLOR",
		GL_DEPTH, "GL_DEPTH",
		GL_STENCIL, "GL_STENCIL",
		GL_RED, "GL_RED",
		GL_RGB8, "GL_RGB8",
		GL_RGBA8, "GL_RGBA8",
		GL_RGB10_A2, "GL_RGB10_A2",
		GL_TEXTURE_BINDING_3D, "GL_TEXTURE_BINDING_3D",
		GL_UNPACK_SKIP_IMAGES, "GL_UNPACK_SKIP_IMAGES",
		GL_UNPACK_IMAGE_HEIGHT, "GL_UNPACK_IMAGE_HEIGHT",
		GL_TEXTURE_3D, "GL_TEXTURE_3D",
		GL_TEXTURE_WRAP_R, "GL_TEXTURE_WRAP_R",
		GL_MAX_3D_TEXTURE_SIZE, "GL_MAX_3D_TEXTURE_SIZE",
		GL_UNSIGNED_INT_2_10_10_10_REV, "GL_UNSIGNED_INT_2_10_10_10_REV",
		GL_MAX_ELEMENTS_VERTICES, "GL_MAX_ELEMENTS_VERTICES",
		GL_MAX_ELEMENTS_INDICES, "GL_MAX_ELEMENTS_INDICES",
		GL_TEXTURE_MIN_LOD, "GL_TEXTURE_MIN_LOD",
		GL_TEXTURE_MAX_LOD, "GL_TEXTURE_MAX_LOD",
		GL_TEXTURE_BASE_LEVEL, "GL_TEXTURE_BASE_LEVEL",
		GL_TEXTURE_MAX_LEVEL, "GL_TEXTURE_MAX_LEVEL",
		GL_MIN, "GL_MIN",
		GL_MAX, "GL_MAX",
		GL_DEPTH_COMPONENT24, "GL_DEPTH_COMPONENT24",
		GL_MAX_TEXTURE_LOD_BIAS, "GL_MAX_TEXTURE_LOD_BIAS",
		GL_TEXTURE_COMPARE_MODE, "GL_TEXTURE_COMPARE_MODE",
		GL_TEXTURE_COMPARE_FUNC, "GL_TEXTURE_COMPARE_FUNC",
		GL_CURRENT_QUERY, "GL_CURRENT_QUERY",
		GL_QUERY_RESULT, "GL_QUERY_RESULT",
		GL_QUERY_RESULT_AVAILABLE, "GL_QUERY_RESULT_AVAILABLE",
		GL_BUFFER_MAPPED, "GL_BUFFER_MAPPED",
		GL_BUFFER_MAP_POINTER, "GL_BUFFER_MAP_POINTER",
		GL_STREAM_READ, "GL_STREAM_READ",
		GL_STREAM_COPY, "GL_STREAM_COPY",
		GL_STATIC_READ, "GL_STATIC_READ",
		GL_STATIC_COPY, "GL_STATIC_COPY",
		GL_DYNAMIC_READ, "GL_DYNAMIC_READ",
		GL_DYNAMIC_COPY, "GL_DYNAMIC_COPY",
		GL_MAX_DRAW_BUFFERS, "GL_MAX_DRAW_BUFFERS",
		GL_DRAW_BUFFER0, "GL_DRAW_BUFFER0",
		GL_DRAW_BUFFER1, "GL_DRAW_BUFFER1",
		GL_DRAW_BUFFER2, "GL_DRAW_BUFFER2",
		GL_DRAW_BUFFER3, "GL_DRAW_BUFFER3",
		GL_DRAW_BUFFER4, "GL_DRAW_BUFFER4",
		GL_DRAW_BUFFER5, "GL_DRAW_BUFFER5",
		GL_DRAW_BUFFER6, "GL_DRAW_BUFFER6",
		GL_DRAW_BUFFER7, "GL_DRAW_BUFFER7",
		GL_DRAW_BUFFER8, "GL_DRAW_BUFFER8",
		GL_DRAW_BUFFER9, "GL_DRAW_BUFFER9",
		GL_DRAW_BUFFER10, "GL_DRAW_BUFFER10",
		GL_DRAW_BUFFER11, "GL_DRAW_BUFFER11",
		GL_DRAW_BUFFER12, "GL_DRAW_BUFFER12",
		GL_DRAW_BUFFER13, "GL_DRAW_BUFFER13",
		GL_DRAW_BUFFER14, "GL_DRAW_BUFFER14",
		GL_DRAW_BUFFER15, "GL_DRAW_BUFFER15",
		GL_MAX_FRAGMENT_UNIFORM_COMPONENTS, "GL_MAX_FRAGMENT_UNIFORM_COMPONENTS",
		GL_MAX_VERTEX_UNIFORM_COMPONENTS, "GL_MAX_VERTEX_UNIFORM_COMPONENTS",
		GL_SAMPLER_3D, "GL_SAMPLER_3D",
		GL_SAMPLER_2D_SHADOW, "GL_SAMPLER_2D_SHADOW",
		GL_FRAGMENT_SHADER_DERIVATIVE_HINT, "GL_FRAGMENT_SHADER_DERIVATIVE_HINT",
		GL_PIXEL_PACK_BUFFER, "GL_PIXEL_PACK_BUFFER",
		GL_PIXEL_UNPACK_BUFFER, "GL_PIXEL_UNPACK_BUFFER",
		GL_PIXEL_PACK_BUFFER_BINDING, "GL_PIXEL_PACK_BUFFER_BINDING",
		GL_PIXEL_UNPACK_BUFFER_BINDING, "GL_PIXEL_UNPACK_BUFFER_BINDING",
		GL_FLOAT_MAT2x3, "GL_FLOAT_MAT2x3",
		GL_FLOAT_MAT2x4, "GL_FLOAT_MAT2x4",
		GL_FLOAT_MAT3x2, "GL_FLOAT_MAT3x2",
		GL_FLOAT_MAT3x4, "GL_FLOAT_MAT3x4",
		GL_FLOAT_MAT4x2, "GL_FLOAT_MAT4x2",
		GL_FLOAT_MAT4x3, "GL_FLOAT_MAT4x3",
		GL_SRGB, "GL_SRGB",
		GL_SRGB8, "GL_SRGB8",
		GL_SRGB8_ALPHA8, "GL_SRGB8_ALPHA8",
		GL_COMPARE_REF_TO_TEXTURE, "GL_COMPARE_REF_TO_TEXTURE",
		GL_MAJOR_VERSION, "GL_MAJOR_VERSION",
		GL_MINOR_VERSION, "GL_MINOR_VERSION",
		GL_NUM_EXTENSIONS, "GL_NUM_EXTENSIONS",
		GL_RGBA32F, "GL_RGBA32F",
		GL_RGB32F, "GL_RGB32F",
		GL_RGBA16F, "GL_RGBA16F",
		GL_RGB16F, "GL_RGB16F",
		GL_VERTEX_ATTRIB_ARRAY_INTEGER, "GL_VERTEX_ATTRIB_ARRAY_INTEGER",
		GL_MAX_ARRAY_TEXTURE_LAYERS, "GL_MAX_ARRAY_TEXTURE_LAYERS",
		GL_MIN_PROGRAM_TEXEL_OFFSET, "GL_MIN_PROGRAM_TEXEL_OFFSET",
		GL_MAX_PROGRAM_TEXEL_OFFSET, "GL_MAX_PROGRAM_TEXEL_OFFSET",
		GL_MAX_VARYING_COMPONENTS, "GL_MAX_VARYING_COMPONENTS",
		GL_TEXTURE_2D_ARRAY, "GL_TEXTURE_2D_ARRAY",
		GL_TEXTURE_BINDING_2D_ARRAY, "GL_TEXTURE_BINDING_2D_ARRAY",
		GL_R11F_G11F_B10F, "GL_R11F_G11F_B10F",
		GL_UNSIGNED_INT_10F_11F_11F_REV, "GL_UNSIGNED_INT_10F_11F_11F_REV",
		GL_RGB9_E5, "GL_RGB9_E5",
		GL_UNSIGNED_INT_5_9_9_9_REV, "GL_UNSIGNED_INT_5_9_9_9_REV",
		GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH, "GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH",
		GL_TRANSFORM_FEEDBACK_BUFFER_MODE, "GL_TRANSFORM_FEEDBACK_BUFFER_MODE",
		GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS, "GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS",
		GL_TRANSFORM_FEEDBACK_VARYINGS, "GL_TRANSFORM_FEEDBACK_VARYINGS",
		GL_TRANSFORM_FEEDBACK_BUFFER_START, "GL_TRANSFORM_FEEDBACK_BUFFER_START",
		GL_TRANSFORM_FEEDBACK_BUFFER_SIZE, "GL_TRANSFORM_FEEDBACK_BUFFER_SIZE",
		GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN, "GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN",
		GL_RASTERIZER_DISCARD, "GL_RASTERIZER_DISCARD",
		GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS, "GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS",
		GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS, "GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS",
		GL_INTERLEAVED_ATTRIBS, "GL_INTERLEAVED_ATTRIBS",
		GL_SEPARATE_ATTRIBS, "GL_SEPARATE_ATTRIBS",
		GL_TRANSFORM_FEEDBACK_BUFFER, "GL_TRANSFORM_FEEDBACK_BUFFER",
		GL_TRANSFORM_FEEDBACK_BUFFER_BINDING, "GL_TRANSFORM_FEEDBACK_BUFFER_BINDING",
		GL_RGBA32UI, "GL_RGBA32UI",
		GL_RGB32UI, "GL_RGB32UI",
		GL_RGBA16UI, "GL_RGBA16UI",
		GL_RGB16UI, "GL_RGB16UI",
		GL_RGBA8UI, "GL_RGBA8UI",
		GL_RGB8UI, "GL_RGB8UI",
		GL_RGBA32I, "GL_RGBA32I",
		GL_RGB32I, "GL_RGB32I",
		GL_RGBA16I, "GL_RGBA16I",
		GL_RGB16I, "GL_RGB16I",
		GL_RGBA8I, "GL_RGBA8I",
		GL_RGB8I, "GL_RGB8I",
		GL_RED_INTEGER, "GL_RED_INTEGER",
		GL_RGB_INTEGER, "GL_RGB_INTEGER",
		GL_RGBA_INTEGER, "GL_RGBA_INTEGER",
		GL_SAMPLER_2D_ARRAY, "GL_SAMPLER_2D_ARRAY",
		GL_SAMPLER_2D_ARRAY_SHADOW, "GL_SAMPLER_2D_ARRAY_SHADOW",
		GL_SAMPLER_CUBE_SHADOW, "GL_SAMPLER_CUBE_SHADOW",
		GL_UNSIGNED_INT_VEC2, "GL_UNSIGNED_INT_VEC2",
		GL_UNSIGNED_INT_VEC3, "GL_UNSIGNED_INT_VEC3",
		GL_UNSIGNED_INT_VEC4, "GL_UNSIGNED_INT_VEC4",
		GL_INT_SAMPLER_2D, "GL_INT_SAMPLER_2D",
		GL_INT_SAMPLER_3D, "GL_INT_SAMPLER_3D",
		GL_INT_SAMPLER_CUBE, "GL_INT_SAMPLER_CUBE",
		GL_INT_SAMPLER_2D_ARRAY, "GL_INT_SAMPLER_2D_ARRAY",
		GL_UNSIGNED_INT_SAMPLER_2D, "GL_UNSIGNED_INT_SAMPLER_2D",
		GL_UNSIGNED_INT_SAMPLER_3D, "GL_UNSIGNED_INT_SAMPLER_3D",
		GL_UNSIGNED_INT_SAMPLER_CUBE, "GL_UNSIGNED_INT_SAMPLER_CUBE",
		GL_UNSIGNED_INT_SAMPLER_2D_ARRAY, "GL_UNSIGNED_INT_SAMPLER_2D_ARRAY",
		GL_BUFFER_ACCESS_FLAGS, "GL_BUFFER_ACCESS_FLAGS",
		GL_BUFFER_MAP_LENGTH, "GL_BUFFER_MAP_LENGTH",
		GL_BUFFER_MAP_OFFSET, "GL_BUFFER_MAP_OFFSET",
		GL_DEPTH_COMPONENT32F, "GL_DEPTH_COMPONENT32F",
		GL_DEPTH32F_STENCIL8, "GL_DEPTH32F_STENCIL8",
		GL_FLOAT_32_UNSIGNED_INT_24_8_REV, "GL_FLOAT_32_UNSIGNED_INT_24_8_REV",
		GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING, "GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING",
		GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE, "GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE",
		GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE, "GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE",
		GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE, "GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE",
		GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE, "GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE",
		GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE, "GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE",
		GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE, "GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE",
		GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE, "GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE",
		GL_FRAMEBUFFER_DEFAULT, "GL_FRAMEBUFFER_DEFAULT",
		GL_FRAMEBUFFER_UNDEFINED, "GL_FRAMEBUFFER_UNDEFINED",
		GL_DEPTH_STENCIL_ATTACHMENT, "GL_DEPTH_STENCIL_ATTACHMENT",
		GL_DEPTH_STENCIL, "GL_DEPTH_STENCIL",
		GL_UNSIGNED_INT_24_8, "GL_UNSIGNED_INT_24_8",
		GL_DEPTH24_STENCIL8, "GL_DEPTH24_STENCIL8",
		GL_UNSIGNED_NORMALIZED, "GL_UNSIGNED_NORMALIZED",
		GL_DRAW_FRAMEBUFFER_BINDING, "GL_DRAW_FRAMEBUFFER_BINDING",
		GL_READ_FRAMEBUFFER, "GL_READ_FRAMEBUFFER",
		GL_DRAW_FRAMEBUFFER, "GL_DRAW_FRAMEBUFFER",
		GL_READ_FRAMEBUFFER_BINDING, "GL_READ_FRAMEBUFFER_BINDING",
		GL_RENDERBUFFER_SAMPLES, "GL_RENDERBUFFER_SAMPLES",
		GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER, "GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER",
		GL_MAX_COLOR_ATTACHMENTS, "GL_MAX_COLOR_ATTACHMENTS",
		GL_COLOR_ATTACHMENT1, "GL_COLOR_ATTACHMENT1",
		GL_COLOR_ATTACHMENT2, "GL_COLOR_ATTACHMENT2",
		GL_COLOR_ATTACHMENT3, "GL_COLOR_ATTACHMENT3",
		GL_COLOR_ATTACHMENT4, "GL_COLOR_ATTACHMENT4",
		GL_COLOR_ATTACHMENT5, "GL_COLOR_ATTACHMENT5",
		GL_COLOR_ATTACHMENT6, "GL_COLOR_ATTACHMENT6",
		GL_COLOR_ATTACHMENT7, "GL_COLOR_ATTACHMENT7",
		GL_COLOR_ATTACHMENT8, "GL_COLOR_ATTACHMENT8",
		GL_COLOR_ATTACHMENT9, "GL_COLOR_ATTACHMENT9",
		GL_COLOR_ATTACHMENT10, "GL_COLOR_ATTACHMENT10",
		GL_COLOR_ATTACHMENT11, "GL_COLOR_ATTACHMENT11",
		GL_COLOR_ATTACHMENT12, "GL_COLOR_ATTACHMENT12",
		GL_COLOR_ATTACHMENT13, "GL_COLOR_ATTACHMENT13",
		GL_COLOR_ATTACHMENT14, "GL_COLOR_ATTACHMENT14",
		GL_COLOR_ATTACHMENT15, "GL_COLOR_ATTACHMENT15",
		GL_COLOR_ATTACHMENT16, "GL_COLOR_ATTACHMENT16",
		GL_COLOR_ATTACHMENT17, "GL_COLOR_ATTACHMENT17",
		GL_COLOR_ATTACHMENT18, "GL_COLOR_ATTACHMENT18",
		GL_COLOR_ATTACHMENT19, "GL_COLOR_ATTACHMENT19",
		GL_COLOR_ATTACHMENT20, "GL_COLOR_ATTACHMENT20",
		GL_COLOR_ATTACHMENT21, "GL_COLOR_ATTACHMENT21",
		GL_COLOR_ATTACHMENT22, "GL_COLOR_ATTACHMENT22",
		GL_COLOR_ATTACHMENT23, "GL_COLOR_ATTACHMENT23",
		GL_COLOR_ATTACHMENT24, "GL_COLOR_ATTACHMENT24",
		GL_COLOR_ATTACHMENT25, "GL_COLOR_ATTACHMENT25",
		GL_COLOR_ATTACHMENT26, "GL_COLOR_ATTACHMENT26",
		GL_COLOR_ATTACHMENT27, "GL_COLOR_ATTACHMENT27",
		GL_COLOR_ATTACHMENT28, "GL_COLOR_ATTACHMENT28",
		GL_COLOR_ATTACHMENT29, "GL_COLOR_ATTACHMENT29",
		GL_COLOR_ATTACHMENT30, "GL_COLOR_ATTACHMENT30",
		GL_COLOR_ATTACHMENT31, "GL_COLOR_ATTACHMENT31",
		GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE, "GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE",
		GL_MAX_SAMPLES, "GL_MAX_SAMPLES",
		GL_HALF_FLOAT, "GL_HALF_FLOAT",
		GL_MAP_READ_BIT, "GL_MAP_READ_BIT",
		GL_MAP_WRITE_BIT, "GL_MAP_WRITE_BIT",
		GL_MAP_INVALIDATE_RANGE_BIT, "GL_MAP_INVALIDATE_RANGE_BIT",
		GL_MAP_INVALIDATE_BUFFER_BIT, "GL_MAP_INVALIDATE_BUFFER_BIT",
		GL_MAP_FLUSH_EXPLICIT_BIT, "GL_MAP_FLUSH_EXPLICIT_BIT",
		GL_MAP_UNSYNCHRONIZED_BIT, "GL_MAP_UNSYNCHRONIZED_BIT",
		GL_RG, "GL_RG",
		GL_RG_INTEGER, "GL_RG_INTEGER",
		GL_R8, "GL_R8",
		GL_RG8, "GL_RG8",
		GL_R16F, "GL_R16F",
		GL_R32F, "GL_R32F",
		GL_RG16F, "GL_RG16F",
		GL_RG32F, "GL_RG32F",
		GL_R8I, "GL_R8I",
		GL_R8UI, "GL_R8UI",
		GL_R16I, "GL_R16I",
		GL_R16UI, "GL_R16UI",
		GL_R32I, "GL_R32I",
		GL_R32UI, "GL_R32UI",
		GL_RG8I, "GL_RG8I",
		GL_RG8UI, "GL_RG8UI",
		GL_RG16I, "GL_RG16I",
		GL_RG16UI, "GL_RG16UI",
		GL_RG32I, "GL_RG32I",
		GL_RG32UI, "GL_RG32UI",
		GL_VERTEX_ARRAY_BINDING, "GL_VERTEX_ARRAY_BINDING",
		GL_R8_SNORM, "GL_R8_SNORM",
		GL_RG8_SNORM, "GL_RG8_SNORM",
		GL_RGB8_SNORM, "GL_RGB8_SNORM",
		GL_RGBA8_SNORM, "GL_RGBA8_SNORM",
		GL_SIGNED_NORMALIZED, "GL_SIGNED_NORMALIZED",
		GL_PRIMITIVE_RESTART_FIXED_INDEX, "GL_PRIMITIVE_RESTART_FIXED_INDEX",
		GL_COPY_READ_BUFFER, "GL_COPY_READ_BUFFER",
		GL_COPY_WRITE_BUFFER, "GL_COPY_WRITE_BUFFER",
		GL_COPY_READ_BUFFER_BINDING, "GL_COPY_READ_BUFFER_BINDING",
		GL_COPY_WRITE_BUFFER_BINDING, "GL_COPY_WRITE_BUFFER_BINDING",
		GL_UNIFORM_BUFFER, "GL_UNIFORM_BUFFER",
		GL_UNIFORM_BUFFER_BINDING, "GL_UNIFORM_BUFFER_BINDING",
		GL_UNIFORM_BUFFER_START, "GL_UNIFORM_BUFFER_START",
		GL_UNIFORM_BUFFER_SIZE, "GL_UNIFORM_BUFFER_SIZE",
		GL_MAX_VERTEX_UNIFORM_BLOCKS, "GL_MAX_VERTEX_UNIFORM_BLOCKS",
		GL_MAX_FRAGMENT_UNIFORM_BLOCKS, "GL_MAX_FRAGMENT_UNIFORM_BLOCKS",
		GL_MAX_COMBINED_UNIFORM_BLOCKS, "GL_MAX_COMBINED_UNIFORM_BLOCKS",
		GL_MAX_UNIFORM_BUFFER_BINDINGS, "GL_MAX_UNIFORM_BUFFER_BINDINGS",
		GL_MAX_UNIFORM_BLOCK_SIZE, "GL_MAX_UNIFORM_BLOCK_SIZE",
		GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS, "GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS",
		GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS, "GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS",
		GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT, "GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT",
		GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH, "GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH",
		GL_ACTIVE_UNIFORM_BLOCKS, "GL_ACTIVE_UNIFORM_BLOCKS",
		GL_UNIFORM_TYPE, "GL_UNIFORM_TYPE",
		GL_UNIFORM_SIZE, "GL_UNIFORM_SIZE",
		GL_UNIFORM_NAME_LENGTH, "GL_UNIFORM_NAME_LENGTH",
		GL_UNIFORM_BLOCK_INDEX, "GL_UNIFORM_BLOCK_INDEX",
		GL_UNIFORM_OFFSET, "GL_UNIFORM_OFFSET",
		GL_UNIFORM_ARRAY_STRIDE, "GL_UNIFORM_ARRAY_STRIDE",
		GL_UNIFORM_MATRIX_STRIDE, "GL_UNIFORM_MATRIX_STRIDE",
		GL_UNIFORM_IS_ROW_MAJOR, "GL_UNIFORM_IS_ROW_MAJOR",
		GL_UNIFORM_BLOCK_BINDING, "GL_UNIFORM_BLOCK_BINDING",
		GL_UNIFORM_BLOCK_DATA_SIZE, "GL_UNIFORM_BLOCK_DATA_SIZE",
		GL_UNIFORM_BLOCK_NAME_LENGTH, "GL_UNIFORM_BLOCK_NAME_LENGTH",
		GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS, "GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS",
		GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES, "GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES",
		GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER, "GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER",
		GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER, "GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER",
		GL_INVALID_INDEX, "GL_INVALID_INDEX",
		GL_MAX_VERTEX_OUTPUT_COMPONENTS, "GL_MAX_VERTEX_OUTPUT_COMPONENTS",
		GL_MAX_FRAGMENT_INPUT_COMPONENTS, "GL_MAX_FRAGMENT_INPUT_COMPONENTS",
		GL_MAX_SERVER_WAIT_TIMEOUT, "GL_MAX_SERVER_WAIT_TIMEOUT",
		GL_OBJECT_TYPE, "GL_OBJECT_TYPE",
		GL_SYNC_CONDITION, "GL_SYNC_CONDITION",
		GL_SYNC_STATUS, "GL_SYNC_STATUS",
		GL_SYNC_FLAGS, "GL_SYNC_FLAGS",
		GL_SYNC_FENCE, "GL_SYNC_FENCE",
		GL_SYNC_GPU_COMMANDS_COMPLETE, "GL_SYNC_GPU_COMMANDS_COMPLETE",
		GL_UNSIGNALED, "GL_UNSIGNALED",
		GL_SIGNALED, "GL_SIGNALED",
		GL_ALREADY_SIGNALED, "GL_ALREADY_SIGNALED",
		GL_TIMEOUT_EXPIRED, "GL_TIMEOUT_EXPIRED",
		GL_CONDITION_SATISFIED, "GL_CONDITION_SATISFIED",
		GL_WAIT_FAILED, "GL_WAIT_FAILED",
		GL_SYNC_FLUSH_COMMANDS_BIT, "GL_SYNC_FLUSH_COMMANDS_BIT",
		GL_VERTEX_ATTRIB_ARRAY_DIVISOR, "GL_VERTEX_ATTRIB_ARRAY_DIVISOR",
		GL_ANY_SAMPLES_PASSED, "GL_ANY_SAMPLES_PASSED",
		GL_ANY_SAMPLES_PASSED_CONSERVATIVE, "GL_ANY_SAMPLES_PASSED_CONSERVATIVE",
		GL_SAMPLER_BINDING, "GL_SAMPLER_BINDING",
		GL_RGB10_A2UI, "GL_RGB10_A2UI",
		GL_TEXTURE_SWIZZLE_R, "GL_TEXTURE_SWIZZLE_R",
		GL_TEXTURE_SWIZZLE_G, "GL_TEXTURE_SWIZZLE_G",
		GL_TEXTURE_SWIZZLE_B, "GL_TEXTURE_SWIZZLE_B",
		GL_TEXTURE_SWIZZLE_A, "GL_TEXTURE_SWIZZLE_A",
		GL_GREEN, "GL_GREEN",
		GL_BLUE, "GL_BLUE",
		GL_INT_2_10_10_10_REV, "GL_INT_2_10_10_10_REV",
		GL_TRANSFORM_FEEDBACK, "GL_TRANSFORM_FEEDBACK",
		GL_TRANSFORM_FEEDBACK_PAUSED, "GL_TRANSFORM_FEEDBACK_PAUSED",
		GL_TRANSFORM_FEEDBACK_ACTIVE, "GL_TRANSFORM_FEEDBACK_ACTIVE",
		GL_TRANSFORM_FEEDBACK_BINDING, "GL_TRANSFORM_FEEDBACK_BINDING",
		GL_PROGRAM_BINARY_RETRIEVABLE_HINT, "GL_PROGRAM_BINARY_RETRIEVABLE_HINT",
		GL_PROGRAM_BINARY_LENGTH, "GL_PROGRAM_BINARY_LENGTH",
		GL_NUM_PROGRAM_BINARY_FORMATS, "GL_NUM_PROGRAM_BINARY_FORMATS",
		GL_PROGRAM_BINARY_FORMATS, "GL_PROGRAM_BINARY_FORMATS",
		GL_COMPRESSED_R11_EAC, "GL_COMPRESSED_R11_EAC",
		GL_COMPRESSED_SIGNED_R11_EAC, "GL_COMPRESSED_SIGNED_R11_EAC",
		GL_COMPRESSED_RG11_EAC, "GL_COMPRESSED_RG11_EAC",
		GL_COMPRESSED_SIGNED_RG11_EAC, "GL_COMPRESSED_SIGNED_RG11_EAC",
		GL_COMPRESSED_RGB8_ETC2, "GL_COMPRESSED_RGB8_ETC2",
		GL_COMPRESSED_SRGB8_ETC2, "GL_COMPRESSED_SRGB8_ETC2",
		GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2, "GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2",
		GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2, "GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2",
		GL_COMPRESSED_RGBA8_ETC2_EAC, "GL_COMPRESSED_RGBA8_ETC2_EAC",
		GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC, "GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC",
		GL_TEXTURE_IMMUTABLE_FORMAT, "GL_TEXTURE_IMMUTABLE_FORMAT",
		GL_MAX_ELEMENT_INDEX, "GL_MAX_ELEMENT_INDEX",
		GL_NUM_SAMPLE_COUNTS, "GL_NUM_SAMPLE_COUNTS",
		GL_TEXTURE_IMMUTABLE_LEVELS, "GL_TEXTURE_IMMUTABLE_LEVELS",
		GL_COMPUTE_SHADER, "GL_COMPUTE_SHADER",
		GL_MAX_COMPUTE_UNIFORM_BLOCKS, "GL_MAX_COMPUTE_UNIFORM_BLOCKS",
		GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS, "GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS",
		GL_MAX_COMPUTE_IMAGE_UNIFORMS, "GL_MAX_COMPUTE_IMAGE_UNIFORMS",
		GL_MAX_COMPUTE_SHARED_MEMORY_SIZE, "GL_MAX_COMPUTE_SHARED_MEMORY_SIZE",
		GL_MAX_COMPUTE_UNIFORM_COMPONENTS, "GL_MAX_COMPUTE_UNIFORM_COMPONENTS",
		GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS, "GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS",
		GL_MAX_COMPUTE_ATOMIC_COUNTERS, "GL_MAX_COMPUTE_ATOMIC_COUNTERS",
		GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS, "GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS",
		GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS, "GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS",
		GL_MAX_COMPUTE_WORK_GROUP_COUNT, "GL_MAX_COMPUTE_WORK_GROUP_COUNT",
		GL_MAX_COMPUTE_WORK_GROUP_SIZE, "GL_MAX_COMPUTE_WORK_GROUP_SIZE",
		GL_COMPUTE_WORK_GROUP_SIZE, "GL_COMPUTE_WORK_GROUP_SIZE",
		GL_DISPATCH_INDIRECT_BUFFER, "GL_DISPATCH_INDIRECT_BUFFER",
		GL_DISPATCH_INDIRECT_BUFFER_BINDING, "GL_DISPATCH_INDIRECT_BUFFER_BINDING",
		GL_COMPUTE_SHADER_BIT, "GL_COMPUTE_SHADER_BIT",
		GL_DRAW_INDIRECT_BUFFER, "GL_DRAW_INDIRECT_BUFFER",
		GL_DRAW_INDIRECT_BUFFER_BINDING, "GL_DRAW_INDIRECT_BUFFER_BINDING",
		GL_MAX_UNIFORM_LOCATIONS, "GL_MAX_UNIFORM_LOCATIONS",
		GL_FRAMEBUFFER_DEFAULT_WIDTH, "GL_FRAMEBUFFER_DEFAULT_WIDTH",
		GL_FRAMEBUFFER_DEFAULT_HEIGHT, "GL_FRAMEBUFFER_DEFAULT_HEIGHT",
		GL_FRAMEBUFFER_DEFAULT_SAMPLES, "GL_FRAMEBUFFER_DEFAULT_SAMPLES",
		GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS, "GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS",
		GL_MAX_FRAMEBUFFER_WIDTH, "GL_MAX_FRAMEBUFFER_WIDTH",
		GL_MAX_FRAMEBUFFER_HEIGHT, "GL_MAX_FRAMEBUFFER_HEIGHT",
		GL_MAX_FRAMEBUFFER_SAMPLES, "GL_MAX_FRAMEBUFFER_SAMPLES",
		GL_UNIFORM, "GL_UNIFORM",
		GL_UNIFORM_BLOCK, "GL_UNIFORM_BLOCK",
		GL_PROGRAM_INPUT, "GL_PROGRAM_INPUT",
		GL_PROGRAM_OUTPUT, "GL_PROGRAM_OUTPUT",
		GL_BUFFER_VARIABLE, "GL_BUFFER_VARIABLE",
		GL_SHADER_STORAGE_BLOCK, "GL_SHADER_STORAGE_BLOCK",
		GL_ATOMIC_COUNTER_BUFFER, "GL_ATOMIC_COUNTER_BUFFER",
		GL_TRANSFORM_FEEDBACK_VARYING, "GL_TRANSFORM_FEEDBACK_VARYING",
		GL_ACTIVE_RESOURCES, "GL_ACTIVE_RESOURCES",
		GL_MAX_NAME_LENGTH, "GL_MAX_NAME_LENGTH",
		GL_MAX_NUM_ACTIVE_VARIABLES, "GL_MAX_NUM_ACTIVE_VARIABLES",
		GL_NAME_LENGTH, "GL_NAME_LENGTH",
		GL_TYPE, "GL_TYPE",
		GL_ARRAY_SIZE, "GL_ARRAY_SIZE",
		GL_OFFSET, "GL_OFFSET",
		GL_BLOCK_INDEX, "GL_BLOCK_INDEX",
		GL_ARRAY_STRIDE, "GL_ARRAY_STRIDE",
		GL_MATRIX_STRIDE, "GL_MATRIX_STRIDE",
		GL_IS_ROW_MAJOR, "GL_IS_ROW_MAJOR",
		GL_ATOMIC_COUNTER_BUFFER_INDEX, "GL_ATOMIC_COUNTER_BUFFER_INDEX",
		GL_BUFFER_BINDING, "GL_BUFFER_BINDING",
		GL_BUFFER_DATA_SIZE, "GL_BUFFER_DATA_SIZE",
		GL_NUM_ACTIVE_VARIABLES, "GL_NUM_ACTIVE_VARIABLES",
		GL_ACTIVE_VARIABLES, "GL_ACTIVE_VARIABLES",
		GL_REFERENCED_BY_VERTEX_SHADER, "GL_REFERENCED_BY_VERTEX_SHADER",
		GL_REFERENCED_BY_FRAGMENT_SHADER, "GL_REFERENCED_BY_FRAGMENT_SHADER",
		GL_REFERENCED_BY_COMPUTE_SHADER, "GL_REFERENCED_BY_COMPUTE_SHADER",
		GL_TOP_LEVEL_ARRAY_SIZE, "GL_TOP_LEVEL_ARRAY_SIZE",
		GL_TOP_LEVEL_ARRAY_STRIDE, "GL_TOP_LEVEL_ARRAY_STRIDE",
		GL_LOCATION, "GL_LOCATION",
		GL_VERTEX_SHADER_BIT, "GL_VERTEX_SHADER_BIT",
		GL_FRAGMENT_SHADER_BIT, "GL_FRAGMENT_SHADER_BIT",
		GL_ALL_SHADER_BITS, "GL_ALL_SHADER_BITS",
		GL_PROGRAM_SEPARABLE, "GL_PROGRAM_SEPARABLE",
		GL_ACTIVE_PROGRAM, "GL_ACTIVE_PROGRAM",
		GL_PROGRAM_PIPELINE_BINDING, "GL_PROGRAM_PIPELINE_BINDING",
		GL_ATOMIC_COUNTER_BUFFER_BINDING, "GL_ATOMIC_COUNTER_BUFFER_BINDING",
		GL_ATOMIC_COUNTER_BUFFER_START, "GL_ATOMIC_COUNTER_BUFFER_START",
		GL_ATOMIC_COUNTER_BUFFER_SIZE, "GL_ATOMIC_COUNTER_BUFFER_SIZE",
		GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS, "GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS",
		GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS, "GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS",
		GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS, "GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS",
		GL_MAX_VERTEX_ATOMIC_COUNTERS, "GL_MAX_VERTEX_ATOMIC_COUNTERS",
		GL_MAX_FRAGMENT_ATOMIC_COUNTERS, "GL_MAX_FRAGMENT_ATOMIC_COUNTERS",
		GL_MAX_COMBINED_ATOMIC_COUNTERS, "GL_MAX_COMBINED_ATOMIC_COUNTERS",
		GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE, "GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE",
		GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS, "GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS",
		GL_ACTIVE_ATOMIC_COUNTER_BUFFERS, "GL_ACTIVE_ATOMIC_COUNTER_BUFFERS",
		GL_UNSIGNED_INT_ATOMIC_COUNTER, "GL_UNSIGNED_INT_ATOMIC_COUNTER",
		GL_MAX_IMAGE_UNITS, "GL_MAX_IMAGE_UNITS",
		GL_MAX_VERTEX_IMAGE_UNIFORMS, "GL_MAX_VERTEX_IMAGE_UNIFORMS",
		GL_MAX_FRAGMENT_IMAGE_UNIFORMS, "GL_MAX_FRAGMENT_IMAGE_UNIFORMS",
		GL_MAX_COMBINED_IMAGE_UNIFORMS, "GL_MAX_COMBINED_IMAGE_UNIFORMS",
		GL_IMAGE_BINDING_NAME, "GL_IMAGE_BINDING_NAME",
		GL_IMAGE_BINDING_LEVEL, "GL_IMAGE_BINDING_LEVEL",
		GL_IMAGE_BINDING_LAYERED, "GL_IMAGE_BINDING_LAYERED",
		GL_IMAGE_BINDING_LAYER, "GL_IMAGE_BINDING_LAYER",
		GL_IMAGE_BINDING_ACCESS, "GL_IMAGE_BINDING_ACCESS",
		GL_IMAGE_BINDING_FORMAT, "GL_IMAGE_BINDING_FORMAT",
		GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT, "GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT",
		GL_ELEMENT_ARRAY_BARRIER_BIT, "GL_ELEMENT_ARRAY_BARRIER_BIT",
		GL_UNIFORM_BARRIER_BIT, "GL_UNIFORM_BARRIER_BIT",
		GL_TEXTURE_FETCH_BARRIER_BIT, "GL_TEXTURE_FETCH_BARRIER_BIT",
		GL_SHADER_IMAGE_ACCESS_BARRIER_BIT, "GL_SHADER_IMAGE_ACCESS_BARRIER_BIT",
		GL_COMMAND_BARRIER_BIT, "GL_COMMAND_BARRIER_BIT",
		GL_PIXEL_BUFFER_BARRIER_BIT, "GL_PIXEL_BUFFER_BARRIER_BIT",
		GL_TEXTURE_UPDATE_BARRIER_BIT, "GL_TEXTURE_UPDATE_BARRIER_BIT",
		GL_BUFFER_UPDATE_BARRIER_BIT, "GL_BUFFER_UPDATE_BARRIER_BIT",
		GL_FRAMEBUFFER_BARRIER_BIT, "GL_FRAMEBUFFER_BARRIER_BIT",
		GL_TRANSFORM_FEEDBACK_BARRIER_BIT, "GL_TRANSFORM_FEEDBACK_BARRIER_BIT",
		GL_ATOMIC_COUNTER_BARRIER_BIT, "GL_ATOMIC_COUNTER_BARRIER_BIT",
		GL_ALL_BARRIER_BITS, "GL_ALL_BARRIER_BITS",
		GL_IMAGE_2D, "GL_IMAGE_2D",
		GL_IMAGE_3D, "GL_IMAGE_3D",
		GL_IMAGE_CUBE, "GL_IMAGE_CUBE",
		GL_IMAGE_2D_ARRAY, "GL_IMAGE_2D_ARRAY",
		GL_INT_IMAGE_2D, "GL_INT_IMAGE_2D",
		GL_INT_IMAGE_3D, "GL_INT_IMAGE_3D",
		GL_INT_IMAGE_CUBE, "GL_INT_IMAGE_CUBE",
		GL_INT_IMAGE_2D_ARRAY, "GL_INT_IMAGE_2D_ARRAY",
		GL_UNSIGNED_INT_IMAGE_2D, "GL_UNSIGNED_INT_IMAGE_2D",
		GL_UNSIGNED_INT_IMAGE_3D, "GL_UNSIGNED_INT_IMAGE_3D",
		GL_UNSIGNED_INT_IMAGE_CUBE, "GL_UNSIGNED_INT_IMAGE_CUBE",
		GL_UNSIGNED_INT_IMAGE_2D_ARRAY, "GL_UNSIGNED_INT_IMAGE_2D_ARRAY",
		GL_IMAGE_FORMAT_COMPATIBILITY_TYPE, "GL_IMAGE_FORMAT_COMPATIBILITY_TYPE",
		GL_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE, "GL_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE",
		GL_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS, "GL_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS",
		GL_READ_ONLY, "GL_READ_ONLY",
		GL_WRITE_ONLY, "GL_WRITE_ONLY",
		GL_READ_WRITE, "GL_READ_WRITE",
		GL_SHADER_STORAGE_BUFFER, "GL_SHADER_STORAGE_BUFFER",
		GL_SHADER_STORAGE_BUFFER_BINDING, "GL_SHADER_STORAGE_BUFFER_BINDING",
		GL_SHADER_STORAGE_BUFFER_START, "GL_SHADER_STORAGE_BUFFER_START",
		GL_SHADER_STORAGE_BUFFER_SIZE, "GL_SHADER_STORAGE_BUFFER_SIZE",
		GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS, "GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS",
		GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS, "GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS",
		GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS, "GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS",
		GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS, "GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS",
		GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS, "GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS",
		GL_MAX_SHADER_STORAGE_BLOCK_SIZE, "GL_MAX_SHADER_STORAGE_BLOCK_SIZE",
		GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT, "GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT",
		GL_SHADER_STORAGE_BARRIER_BIT, "GL_SHADER_STORAGE_BARRIER_BIT",
		GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES, "GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES",
		GL_DEPTH_STENCIL_TEXTURE_MODE, "GL_DEPTH_STENCIL_TEXTURE_MODE",
		GL_STENCIL_INDEX, "GL_STENCIL_INDEX",
		GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET, "GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET",
		GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET, "GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET",
		GL_SAMPLE_POSITION, "GL_SAMPLE_POSITION",
		GL_SAMPLE_MASK, "GL_SAMPLE_MASK",
		GL_SAMPLE_MASK_VALUE, "GL_SAMPLE_MASK_VALUE",
		GL_TEXTURE_2D_MULTISAMPLE, "GL_TEXTURE_2D_MULTISAMPLE",
		GL_MAX_SAMPLE_MASK_WORDS, "GL_MAX_SAMPLE_MASK_WORDS",
		GL_MAX_COLOR_TEXTURE_SAMPLES, "GL_MAX_COLOR_TEXTURE_SAMPLES",
		GL_MAX_DEPTH_TEXTURE_SAMPLES, "GL_MAX_DEPTH_TEXTURE_SAMPLES",
		GL_MAX_INTEGER_SAMPLES, "GL_MAX_INTEGER_SAMPLES",
		GL_TEXTURE_BINDING_2D_MULTISAMPLE, "GL_TEXTURE_BINDING_2D_MULTISAMPLE",
		GL_TEXTURE_SAMPLES, "GL_TEXTURE_SAMPLES",
		GL_TEXTURE_FIXED_SAMPLE_LOCATIONS, "GL_TEXTURE_FIXED_SAMPLE_LOCATIONS",
		GL_TEXTURE_WIDTH, "GL_TEXTURE_WIDTH",
		GL_TEXTURE_HEIGHT, "GL_TEXTURE_HEIGHT",
		GL_TEXTURE_DEPTH, "GL_TEXTURE_DEPTH",
		GL_TEXTURE_INTERNAL_FORMAT, "GL_TEXTURE_INTERNAL_FORMAT",
		GL_TEXTURE_RED_SIZE, "GL_TEXTURE_RED_SIZE",
		GL_TEXTURE_GREEN_SIZE, "GL_TEXTURE_GREEN_SIZE",
		GL_TEXTURE_BLUE_SIZE, "GL_TEXTURE_BLUE_SIZE",
		GL_TEXTURE_ALPHA_SIZE, "GL_TEXTURE_ALPHA_SIZE",
		GL_TEXTURE_DEPTH_SIZE, "GL_TEXTURE_DEPTH_SIZE",
		GL_TEXTURE_STENCIL_SIZE, "GL_TEXTURE_STENCIL_SIZE",
		GL_TEXTURE_SHARED_SIZE, "GL_TEXTURE_SHARED_SIZE",
		GL_TEXTURE_RED_TYPE, "GL_TEXTURE_RED_TYPE",
		GL_TEXTURE_GREEN_TYPE, "GL_TEXTURE_GREEN_TYPE",
		GL_TEXTURE_BLUE_TYPE, "GL_TEXTURE_BLUE_TYPE",
		GL_TEXTURE_ALPHA_TYPE, "GL_TEXTURE_ALPHA_TYPE",
		GL_TEXTURE_DEPTH_TYPE, "GL_TEXTURE_DEPTH_TYPE",
		GL_TEXTURE_COMPRESSED, "GL_TEXTURE_COMPRESSED",
		GL_SAMPLER_2D_MULTISAMPLE, "GL_SAMPLER_2D_MULTISAMPLE",
		GL_INT_SAMPLER_2D_MULTISAMPLE, "GL_INT_SAMPLER_2D_MULTISAMPLE",
		GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE, "GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE",
		GL_VERTEX_ATTRIB_BINDING, "GL_VERTEX_ATTRIB_BINDING",
		GL_VERTEX_ATTRIB_RELATIVE_OFFSET, "GL_VERTEX_ATTRIB_RELATIVE_OFFSET",
		GL_VERTEX_BINDING_DIVISOR, "GL_VERTEX_BINDING_DIVISOR",
		GL_VERTEX_BINDING_OFFSET, "GL_VERTEX_BINDING_OFFSET",
		GL_VERTEX_BINDING_STRIDE, "GL_VERTEX_BINDING_STRIDE",
		GL_VERTEX_BINDING_BUFFER, "GL_VERTEX_BINDING_BUFFER",
		GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET, "GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET",
		GL_MAX_VERTEX_ATTRIB_BINDINGS, "GL_MAX_VERTEX_ATTRIB_BINDINGS",
		GL_MAX_VERTEX_ATTRIB_STRIDE, "GL_MAX_VERTEX_ATTRIB_STRIDE",
	};

	typedef struct GLFormat {
		VkFormat format;
		GLenum internalFormat;
		GLenum externalFormat;
		GLenum type;
	} GLFormat;

	static const GLFormat glFormats[] = {
		VK_FORMAT_R8_UNORM, GL_R8, GL_RED, GL_UNSIGNED_BYTE,
		VK_FORMAT_R8_SNORM, GL_R8_SNORM, GL_RED, GL_BYTE,
		VK_FORMAT_R16_SFLOAT, GL_R16F, GL_RED, GL_FLOAT,
		VK_FORMAT_R32_SFLOAT, GL_R32F, GL_RED, GL_FLOAT,
		VK_FORMAT_R8_UINT, GL_R8UI, GL_RED_INTEGER, GL_UNSIGNED_BYTE,
		VK_FORMAT_R8_SINT, GL_R8I, GL_RED_INTEGER, GL_BYTE,
		VK_FORMAT_R16_UINT, GL_R16UI, GL_RED_INTEGER, GL_UNSIGNED_SHORT,
		VK_FORMAT_R16_SINT, GL_R16I, GL_RED_INTEGER, GL_SHORT,
		VK_FORMAT_R32_UINT, GL_R32UI, GL_RED_INTEGER, GL_UNSIGNED_INT,
		VK_FORMAT_R32_SINT, GL_R32I, GL_RED_INTEGER, GL_INT,
		VK_FORMAT_R8G8_UNORM, GL_RG8, GL_RG, GL_UNSIGNED_BYTE,
		VK_FORMAT_R8G8_SNORM, GL_RG8_SNORM, GL_RG, GL_BYTE,
		VK_FORMAT_R16G16_SFLOAT, GL_RG16F, GL_RG, GL_FLOAT,
		VK_FORMAT_R32G32_SFLOAT, GL_RG32F, GL_RG, GL_FLOAT,
		VK_FORMAT_R8G8_UINT, GL_RG8UI, GL_RG_INTEGER, GL_UNSIGNED_BYTE,
		VK_FORMAT_R8G8_SINT, GL_RG8I, GL_RG_INTEGER, GL_BYTE,
		VK_FORMAT_R16G16_UINT, GL_RG16UI, GL_RG_INTEGER, GL_UNSIGNED_SHORT,
		VK_FORMAT_R16G16_SINT, GL_RG16I, GL_RG_INTEGER, GL_SHORT,
		VK_FORMAT_R32G32_UINT, GL_RG32UI, GL_RG_INTEGER, GL_UNSIGNED_INT,
		VK_FORMAT_R32G32_SINT, GL_RG32I, GL_RG_INTEGER, GL_INT,
		VK_FORMAT_R8G8B8_UNORM, GL_RGB8, GL_RGB, GL_UNSIGNED_BYTE,
		VK_FORMAT_R8G8B8_SRGB, GL_SRGB8, GL_RGB, GL_UNSIGNED_BYTE,
		VK_FORMAT_R8G8B8_SNORM, GL_RGB8_SNORM, GL_RGB, GL_BYTE,
		VK_FORMAT_B8G8R8_UNORM, GL_RGB8, GL_RGB, GL_UNSIGNED_BYTE,
		VK_FORMAT_B8G8R8_SRGB, GL_SRGB8, GL_RGB, GL_UNSIGNED_BYTE,
		VK_FORMAT_B8G8R8_SNORM, GL_RGB8_SNORM, GL_RGB, GL_BYTE,
		VK_FORMAT_R5G6B5_UNORM_PACK16, GL_RGB565, GL_RGB, GL_UNSIGNED_BYTE,
		VK_FORMAT_B10G11R11_UFLOAT_PACK32, GL_R11F_G11F_B10F, GL_RGB, GL_FLOAT,
		VK_FORMAT_E5B9G9R9_UFLOAT_PACK32, GL_RGB9_E5, GL_RGB, GL_FLOAT,
		VK_FORMAT_R16G16B16_SFLOAT, GL_RGB16F, GL_RGB, GL_FLOAT,
		VK_FORMAT_R32G32B32_SFLOAT, GL_RGB32F, GL_RGB, GL_FLOAT,
		VK_FORMAT_R8G8B8_UINT, GL_RGB8UI, GL_RGB_INTEGER, GL_UNSIGNED_BYTE,
		VK_FORMAT_R8G8B8_SINT, GL_RGB8I, GL_RGB_INTEGER, GL_BYTE,
		VK_FORMAT_B8G8R8_UINT, GL_RGB8UI, GL_RGB_INTEGER, GL_UNSIGNED_BYTE,
		VK_FORMAT_B8G8R8_SINT, GL_RGB8I, GL_RGB_INTEGER, GL_BYTE,
		VK_FORMAT_R16G16B16_UINT, GL_RGB16UI, GL_RGB_INTEGER, GL_UNSIGNED_SHORT,
		VK_FORMAT_R16G16B16_SINT, GL_RGB16I, GL_RGB_INTEGER, GL_SHORT,
		VK_FORMAT_R32G32B32_UINT, GL_RGB32UI, GL_RGB_INTEGER, GL_UNSIGNED_INT,
		VK_FORMAT_R32G32B32_SINT, GL_RGB32I, GL_RGB_INTEGER, GL_INT,
		VK_FORMAT_R8G8B8A8_UNORM, GL_RGBA8, GL_RGBA, GL_UNSIGNED_BYTE,
		VK_FORMAT_R8G8B8A8_SRGB, GL_SRGB8_ALPHA8, GL_RGBA, GL_UNSIGNED_BYTE,
		VK_FORMAT_R8G8B8A8_SNORM, GL_RGBA8_SNORM, GL_RGBA, GL_BYTE,
		VK_FORMAT_B8G8R8A8_UNORM, GL_RGBA8, GL_RGBA, GL_UNSIGNED_BYTE,
		VK_FORMAT_B8G8R8A8_SRGB, GL_SRGB8_ALPHA8, GL_RGBA, GL_UNSIGNED_BYTE,
		VK_FORMAT_B8G8R8A8_SNORM, GL_RGBA8_SNORM, GL_RGBA, GL_BYTE,
		VK_FORMAT_R5G5B5A1_UNORM_PACK16, GL_RGB5_A1, GL_RGBA, GL_UNSIGNED_BYTE,
		VK_FORMAT_R4G4B4A4_UNORM_PACK16, GL_RGBA4, GL_RGBA, GL_UNSIGNED_BYTE,
		VK_FORMAT_A2R10G10B10_UNORM_PACK32, GL_RGB10_A2, GL_RGBA, GL_UNSIGNED_INT_2_10_10_10_REV,
		VK_FORMAT_R16G16B16A16_SFLOAT, GL_RGBA16F, GL_RGBA, GL_FLOAT,
		VK_FORMAT_R32G32B32A32_SFLOAT, GL_RGBA32F, GL_RGBA, GL_FLOAT,
		VK_FORMAT_R8G8B8A8_UINT, GL_RGBA8UI, GL_RGBA_INTEGER, GL_UNSIGNED_BYTE,
		VK_FORMAT_R8G8B8A8_SINT, GL_RGBA8I, GL_RGBA_INTEGER, GL_BYTE,
		VK_FORMAT_B8G8R8A8_UINT, GL_RGBA8UI, GL_RGBA_INTEGER, GL_UNSIGNED_BYTE,
		VK_FORMAT_B8G8R8A8_SINT, GL_RGBA8I, GL_RGBA_INTEGER, GL_BYTE,
		VK_FORMAT_A2R10G10B10_UINT_PACK32, GL_RGB10_A2UI, GL_RGBA_INTEGER, GL_UNSIGNED_INT_2_10_10_10_REV,
		VK_FORMAT_R16G16B16A16_UINT, GL_RGBA16UI, GL_RGBA_INTEGER, GL_UNSIGNED_SHORT,
		VK_FORMAT_R16G16B16A16_SINT, GL_RGBA16I, GL_RGBA_INTEGER, GL_SHORT,
		VK_FORMAT_R32G32B32A32_SINT, GL_RGBA32I, GL_RGBA_INTEGER, GL_INT,
		VK_FORMAT_R32G32B32A32_UINT, GL_RGBA32UI, GL_RGBA_INTEGER, GL_UNSIGNED_INT,
		VK_FORMAT_D16_UNORM, GL_DEPTH_COMPONENT16, GL_DEPTH_COMPONENT, GL_UNSIGNED_SHORT,
		VK_FORMAT_D32_SFLOAT, GL_DEPTH_COMPONENT32F, GL_DEPTH_COMPONENT, GL_FLOAT,
		VK_FORMAT_D24_UNORM_S8_UINT, GL_DEPTH24_STENCIL8, GL_DEPTH_STENCIL, GL_UNSIGNED_INT_24_8,
		VK_FORMAT_D32_SFLOAT_S8_UINT, GL_DEPTH32F_STENCIL8, GL_DEPTH_STENCIL, GL_FLOAT_32_UNSIGNED_INT_24_8_REV,
		VK_FORMAT_S8_UINT, GL_STENCIL_INDEX8, GL_STENCIL_INDEX, GL_UNSIGNED_BYTE,
	};

	const char* CGLES3Helper::glEnumToString(GLenum value)
	{
		for (GLint index = 0; index < sizeof(glEnumStrings) / sizeof(GLEnumString); index++) {
			if (glEnumStrings[index].value == value) {
				return glEnumStrings[index].text;
			}
		}
		return "unknown";
	}

	GLboolean CGLES3Helper::glIsFormatDepthOnly(GLenum format)
	{
		return format == GL_DEPTH_COMPONENT ? GL_TRUE : GL_FALSE;
	}

	GLboolean CGLES3Helper::glIsFormatStencilOnly(GLenum format)
	{
		return format == GL_STENCIL_INDEX ? GL_TRUE : GL_FALSE;
	}

	GLboolean CGLES3Helper::glIsFormatDepthStencil(GLenum format)
	{
		return format == GL_DEPTH_STENCIL ? GL_TRUE : GL_FALSE;
	}

	GLenum CGLES3Helper::glTranslateFormat(VkFormat format, GLenum &internalFormat, GLenum &externalFormat, GLenum &type)
	{
		for (GLint index = 0; index < sizeof(glFormats) / sizeof(GLFormat); index++) {
			if (glFormats[index].format == format) {
				internalFormat = glFormats[index].internalFormat;
				externalFormat = glFormats[index].externalFormat;
				type = glFormats[index].type;
				return GL_NO_ERROR;
			}
		}

		return GL_INVALID_ENUM;
	}

	GLenum CGLES3Helper::glTranslateMagFilter(VkFilter magFilter)
	{
		switch (magFilter) {
		case VK_FILTER_NEAREST: return GL_NEAREST;
		case VK_FILTER_LINEAR: return GL_LINEAR;
		default: return GL_INVALID_ENUM;
		}
	}

	GLenum CGLES3Helper::glTranslateMinFilter(VkFilter minFilter, VkSamplerMipmapMode mipmapMode)
	{
		switch (minFilter) {
		case VK_FILTER_NEAREST:
			switch (mipmapMode) {
			case VK_SAMPLER_MIPMAP_MODE_NEAREST: return GL_NEAREST_MIPMAP_NEAREST;
			case VK_SAMPLER_MIPMAP_MODE_LINEAR: return GL_NEAREST_MIPMAP_LINEAR;
			default: return GL_INVALID_ENUM;
			}
			break;
		case VK_FILTER_LINEAR:
			switch (mipmapMode) {
			case VK_SAMPLER_MIPMAP_MODE_NEAREST: return GL_LINEAR_MIPMAP_NEAREST;
			case VK_SAMPLER_MIPMAP_MODE_LINEAR: return GL_LINEAR_MIPMAP_LINEAR;
			default: return GL_INVALID_ENUM;
			}
			break;
		default: return GL_INVALID_ENUM;
		}
	}

	GLenum CGLES3Helper::glTranslateAddressMode(VkSamplerAddressMode addressMode)
	{
		switch (addressMode) {
		case VK_SAMPLER_ADDRESS_MODE_REPEAT: return GL_REPEAT;
		case VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT: return GL_MIRRORED_REPEAT;
		case VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE: return GL_CLAMP_TO_EDGE;
//		case VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER: return GL_CLAMP_TO_BORDER;
		default: return GL_INVALID_ENUM;
		}
	}

	GLenum CGLES3Helper::glTranslateStencilOp(VkStencilOp op)
	{
		switch (op) {
		case VK_STENCIL_OP_KEEP: return GL_KEEP;
		case VK_STENCIL_OP_ZERO: return GL_ZERO;
		case VK_STENCIL_OP_REPLACE: return GL_REPLACE;
		case VK_STENCIL_OP_INCREMENT_AND_CLAMP: return GL_INCR;
		case VK_STENCIL_OP_DECREMENT_AND_CLAMP: return GL_DECR;
		case VK_STENCIL_OP_INVERT: return GL_INVERT;
		case VK_STENCIL_OP_INCREMENT_AND_WRAP: return GL_INCR_WRAP;
		case VK_STENCIL_OP_DECREMENT_AND_WRAP: return GL_DECR_WRAP;
		default: return GL_INVALID_ENUM;
		}
	}

	GLenum CGLES3Helper::glTranslateCompareOp(VkCompareOp op)
	{
		switch (op) {
		case VK_COMPARE_OP_NEVER: return GL_NEVER;
		case VK_COMPARE_OP_LESS: return GL_LESS;
		case VK_COMPARE_OP_EQUAL: return GL_EQUAL;
		case VK_COMPARE_OP_LESS_OR_EQUAL: return GL_LEQUAL;
		case VK_COMPARE_OP_GREATER: return GL_GREATER;
		case VK_COMPARE_OP_NOT_EQUAL: return GL_NOTEQUAL;
		case VK_COMPARE_OP_GREATER_OR_EQUAL: return GL_GEQUAL;
		case VK_COMPARE_OP_ALWAYS: return GL_ALWAYS;
		default: return GL_INVALID_ENUM;
		}
	}

	GLenum CGLES3Helper::glTranslateBlendOp(VkBlendOp op)
	{
		switch (op) {
		case VK_BLEND_OP_ADD: return GL_FUNC_ADD;
		case VK_BLEND_OP_SUBTRACT: return GL_FUNC_SUBTRACT;
		case VK_BLEND_OP_REVERSE_SUBTRACT: return GL_FUNC_REVERSE_SUBTRACT;
		case VK_BLEND_OP_MIN: return GL_MIN;
		case VK_BLEND_OP_MAX: return GL_MAX;
		default: return GL_INVALID_ENUM;
		}
	}

	GLenum CGLES3Helper::glTranslateBlendFactor(VkBlendFactor factor)
	{
		switch (factor) {
		case VK_BLEND_FACTOR_ZERO: return GL_ZERO;
		case VK_BLEND_FACTOR_ONE: return GL_ONE;
		case VK_BLEND_FACTOR_SRC_COLOR: return GL_SRC_COLOR;
		case VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR: return GL_ONE_MINUS_SRC_COLOR;
		case VK_BLEND_FACTOR_DST_COLOR: return GL_DST_COLOR;
		case VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR: return GL_ONE_MINUS_DST_COLOR;
		case VK_BLEND_FACTOR_SRC_ALPHA: return GL_SRC_ALPHA;
		case VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA: return GL_ONE_MINUS_SRC_ALPHA;
		case VK_BLEND_FACTOR_DST_ALPHA: return GL_DST_ALPHA;
		case VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA: return GL_ONE_MINUS_DST_ALPHA;
		case VK_BLEND_FACTOR_CONSTANT_COLOR: return GL_CONSTANT_COLOR;
		case VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR: return GL_ONE_MINUS_CONSTANT_COLOR;
		case VK_BLEND_FACTOR_CONSTANT_ALPHA: return GL_CONSTANT_ALPHA;
		case VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA: return GL_ONE_MINUS_CONSTANT_ALPHA;
		case VK_BLEND_FACTOR_SRC_ALPHA_SATURATE: return GL_SRC_ALPHA_SATURATE;
		//case VK_BLEND_FACTOR_SRC1_COLOR:
		//case VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR:
		//case VK_BLEND_FACTOR_SRC1_ALPHA:
		//case VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA:
		default: return GL_INVALID_ENUM;
		}
	}

	GLenum CGLES3Helper::glTranslateCullMode(VkCullModeFlags cullMode)
	{
		switch (cullMode) {
		case VK_CULL_MODE_FRONT_BIT: return GL_FRONT;
		case VK_CULL_MODE_BACK_BIT: return GL_BACK;
		case VK_CULL_MODE_FRONT_AND_BACK: return GL_FRONT_AND_BACK;
		default: return GL_INVALID_ENUM;
		}
	}

	GLenum CGLES3Helper::glTranslateFrontFace(VkFrontFace frontFace)
	{
		switch (frontFace) {
		case VK_FRONT_FACE_COUNTER_CLOCKWISE: return GL_CCW;
		case VK_FRONT_FACE_CLOCKWISE: return GL_CW;
		default: return GL_INVALID_ENUM;
		}
	}

	GLenum CGLES3Helper::glTranslateStencilFace(VkStencilFaceFlags stencilFace)
	{
		switch (stencilFace) {
		case VK_STENCIL_FACE_FRONT_BIT: return GL_FRONT;
		case VK_STENCIL_FACE_BACK_BIT: return GL_BACK;
		case VK_STENCIL_FRONT_AND_BACK: return GL_FRONT_AND_BACK;
		default: return GL_INVALID_ENUM;
		}
	}

	GLenum CGLES3Helper::glTranslatePrimitiveTopology(VkPrimitiveTopology topology)
	{
		switch (topology) {
		case VK_PRIMITIVE_TOPOLOGY_POINT_LIST: return GL_POINTS;
		case VK_PRIMITIVE_TOPOLOGY_LINE_LIST: return GL_LINES;
		case VK_PRIMITIVE_TOPOLOGY_LINE_STRIP: return GL_LINE_STRIP;
		case VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST: return GL_TRIANGLES;
		case VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP: return GL_TRIANGLE_STRIP;
		case VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN: return GL_TRIANGLE_FAN;
		//case VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY:
		//case VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY:
		//case VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY:
		//case VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY:
		//case VK_PRIMITIVE_TOPOLOGY_PATCH_LIST:
		default: return GL_INVALID_ENUM;
		}
	}

	GLenum CGLES3Helper::glTranslateIndexType(VkIndexType type)
	{
		switch (type) {
		case VK_INDEX_TYPE_UINT16: return GL_UNSIGNED_SHORT;
		case VK_INDEX_TYPE_UINT32: return GL_UNSIGNED_INT;
		default: return GL_INVALID_ENUM;
		}
	}

	GLsizei CGLES3Helper::glGetIndexTypeSize(VkIndexType type)
	{
		switch (type) {
		case VK_INDEX_TYPE_UINT16: return 2;
		case VK_INDEX_TYPE_UINT32: return 4;
		default: return 0;
		}
	}

}
